### ISSUE TITLE
Suggest explicit import in the hello_world example

### ISSUE THREAD

**Issue by ltfschoen** [maciejhirsz/kobold#22]
In the beginner hello_world example, instead of importing everything with `use kobold::prelude::*;` perhaps change to just `use kobold::prelude::{component, html, Html};`

**Comment by maciejhirsz** [comment]
That would have to be `use kobold::{component, html, Html};` if anything, but I don't think that's necessary. The whole point of having a `prelude` is to do a blanket import of everything in it, it is a [common](https://docs.rs/bevy/latest/bevy/prelude/index.html) [pattern](https://docs.rs/yew/latest/yew/prelude/index.html).

Not all crates should have a `prelude`, [people have strong opinions about it](https://www.reddit.com/r/rust/comments/a7pcp2/is_using_a_crateprelude_good_practice/ec54i31/). Personally I think the border here is kind of fuzzy, something like `arrayvec` doesn't need one and shouldn't have one, but things like game engines or web frameworks (if you can call Kobold that) should.

With that in mind I'd rather keep the hello world as is, since using `kobold::prelude::*` is a good pattern here.
